### ISSUE TITLE
Vehicle geolocalization

### ISSUE THREAD

**Issue by dresiwela** [rameau-fr/CCTV-Calib#2]
Where could I find the code for the vehicle geolocalization application?

**Comment by rameau-fr** [comment]
Thank you very much for your interest in this project. 
The geolocation module is not shared in this repository dedicated to the calibration toolbox. This upstream task is mainly used to demonstrate the relevance of the calibration itself. 

However, if you want to geolocalize vehicles given the parameters returned by the calibration toolbox, it can be a relatively simple task; for instance, you can directly use the calculate tomography to project the center of the tracked bounding boxes directly on the satellite map. 
If you need a higher accuracy, the main difficulty is the 3D vehicle detection module, In particular, it is very challenging to train a network able to generalize to any cameras configurations, you might want to refer to some details of the paper to improve this aspect. Also, I have recently spotted a paper that might be of some interest if you would like to train a network for this task: https://[arxiv.org/pdf/2309.01324.pdf](https://arxiv.org/pdf/2309.01324.pdf)
Please let me know if you have any additional questions.

**Comment by dresiwela** [comment]
Thank you for the information I will definitely look into that.

I am actually looking to start a geolocation saas company that provides analytics on cctv feeds and your repo helped me in one of steps I had difficulty with.

From: rameau-fr ***@***.***>
Date: Thursday, 16 November 2023 at 6:38 pm
To: rameau-fr/CCTV-Calib ***@***.***>
Cc: Dre Siwela (Student) ***@***.***>, Author ***@***.***>
Subject: Re: [rameau-fr/CCTV-Calib] Vehicle geolocalization (Issue #2)

Thank you very much for your interest in this project.
The geolocation module is not shared in this repository dedicated to the calibration toolbox. This upstream task is mainly used to demonstrate the relevance of the calibration itself.

However, if you want to geolocalize vehicles given the parameters returned by the calibration toolbox, it can be a relatively simple task; for instance, you can directly use the calculate tomography to project the center of the tracked bounding boxes directly on the satellite map.
If you need a higher accuracy, the main difficulty is the 3D vehicle detection module, In particular, it is very challenging to train a network able to generalize to any cameras configurations, you might want to refer to some details of the paper to improve this aspect. Also, I have recently spotted a paper that might be of some interest if you would like to train a network for this task: https://arxiv.org/pdf/2309.01324.pdf<https://arxiv.org/pdf/2309.01324.pdf>
Please let me know if you have any additional questions.
