### ISSUE TITLE
A tool/extention to connect cameras after calibration

### ISSUE THREAD

**Issue by gyillikci** [rameau-fr/CCTV-Calib#4]
hi Francois again,

I did some tries for indoor environment and looks promising. can you suggest a tool to combine videos according to extrinsic and intrinsic calibrations that CCTV-calib has calculated? for instance like your [video ](https://www.youtube.com/watch?v=RBw5ZZQgbSk)

Best,

Giray

**Comment by rameau-fr** [comment]
Sorry for this delayed reply. I am glad you obtained some preliminary results for your use case!
I have just written the code entirely from scratch to build this video. 
Luckily, it is rather simple; using the intrinsic and extrinsic parameters, I recombine the homography matrix to transform the image coordinates into the map coordinates, and I display the tracked object as points using openCV.
I you need, I can have a look at the code to recombine the homography, let me know if you figured out!

**Comment by gyillikci** [comment]
Hi Francois,

I think I can handle that as you suggested. Let me figure out.

Best,

Giray

**Comment by gyillikci** [comment]
Hi Francois,

Last time you briefly mentioned how to handle the image coordinates to world coordinates and match tracking of cameras. but I bogged down on it and not had a success.
You mentioned the code you used. If it is possible to share, it would be very useful to have it for me. 

Best,

Giray
